### ISSUE TITLE
neuropil correction factor doesn't match with subquantities name

### ISSUE THREAD

**Issue by maiaaan** [yzerlaut/physion#4]
In imaging.Calcium, the neuropil correction factor seems to be set with the constant `NEUROPIL_CORRECTION_FACTOR` which is set to 0.8. 
However, in analysis.read_NWB, in the function list_subquantities, the description of the neuropil corrected fluorescence trace doesn't match with the chosen parameter ("F-0.7*Fneu", "d(F-0.7*Fneu)").

![image](https://github.com/user-attachments/assets/8e177b73-32d0-440c-a7d6-608d914a1046)

**Comment by yzerlaut** [comment]
Yes, that's a deprecated strategy. I was extracting the neuropil correction factor from the `subquantity` string. I just removed those deprecated settings in [d15b0](https://github.com/yzerlaut/physion/commit/d15b0129d7f5994d07ff7f5718e38f23ede3494f).

Now, the `dFoF` is thought to be always built by calling `data.build_dFoF`, like this:
```
data = analysis.read_NWB(filename)
data.build_dFoF() # without arguments, the default params are from imaging/Calcium.py 
```
Or, with arguments:
```
data.build_dFoF(
                   roi_to_neuropil_fluo_inclusion_factor=1.20,
                   neuropil_correction_factor=0.9,
                   method_for_F0='sliding-percentile',
                   percentile=5.,
                   sliding_window=600.)
```
